package br.com.acopara.rotinasweb.repository;

import br.com.acopara.rotinasweb.model.DashboardRca;
import br.com.acopara.rotinasweb.model.DashboardSupervisor;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.transaction.annotation.Transactional;

@Transactional(readOnly = false)
public interface DashboardSupervisorRepository extends JpaRepository<DashboardSupervisor, Long> {

    @Query(value = "SELECT \n" +
            "CODSUPERVISOR SUPERVISOR,\n" +
            "QTPEDIDOS QTPEDIDOS,\n" +
            "QTORCAMENTOS QTORCAMENTOS,\n" +
            "QTORCAMENTOCONVERTIDO QTORCAMENTOCONVERTIDO,\n" +
            "ROUND(CASE WHEN QTORCAMENTOCONVERTIDO <> 0 THEN (QTORCAMENTOCONVERTIDO/QTORCAMENTOS)*100 WHEN QTORCAMENTOCONVERTIDO IS NULL THEN 0 ELSE 0 END, 2) PRODUTIVIDADE,\n" +
            "QTITENS QTITENS,\n" +
            "MEDIAQTITENS MEDIAQTITENS,\n" +
            "QTCLIPOS QTCLIPOS,\n" +
            "TOTPESO TOTPESO,\n" +
            "VLVENDAMES VLVENDAMES,\n" +
            "METAMES METAMES,\n" +
            "ROUND(CASE WHEN VLVENDAMES <> 0 AND METAMES <> 0 THEN ((VLVENDAMES/METAMES)*100) WHEN VLVENDAMES IS NULL THEN 0 ELSE 0 END,2) PERCENTMETAMES,\n" +
            "ROUND(CASE WHEN VLVENDAMES <> 0 THEN (VLVENDAMES/QTPEDIDOS) WHEN VLVENDAMES IS NULL THEN 0 ELSE 0 END,2) TICKETMEDIO,\n" +
            "ROUND(CASE WHEN VLVENDAMES <> 0 THEN ((VLVENDAMES/(TO_NUMBER(TO_CHAR(SYSDATE,'DD')) - (TRUNC(TO_NUMBER(TO_CHAR(SYSDATE,'DD'))/7)))*(ADD_MONTHS(LAST_DAY(TO_char(sysdate,'DD/MM/YYYY')),0) - TRUNC(ADD_MONTHS(TO_char(sysdate,'DD/MM/YYYY'), 0),'MON')) - TRUNC((ADD_MONTHS(LAST_DAY(TO_char(sysdate,'DD/MM/YYYY')),0) - TRUNC(ADD_MONTHS(TO_char(sysdate,'DD/MM/YYYY'), 0),'MON'))/7))) WHEN VLVENDAMES IS NULL THEN 0 ELSE 0 END,2) PROJVENDAS,\n" +
            "VLVENDADIA VLVENDADIA,\n" +
            "METADIA METADIA,\n" +
            "ROUND(CASE WHEN VLVENDADIA <> 0 AND METADIA <> 0 THEN ((VLVENDADIA/METADIA)*100) WHEN VLVENDADIA IS NULL THEN 0 ELSE 0 END,2) PERCENTMETADIA\n" +
            "FROM (SELECT\n" +
            "        PCPEDC.CODSUPERVISOR,\n" +
            "        NVL(PCSUPERV.NOME, '* NAO VINCULADO *') SUPERVISOR,\n" +
            "        COUNT(NVL(PCPEDC.NUMPED,0)) QTPEDIDOS,\n" +
            "        (SELECT COUNT(DISTINCT(PCORCAVENDAC.NUMORCA)) FROM PCORCAVENDAC WHERE PCORCAVENDAC.DATA BETWEEN  trunc(ADD_MONTHS(TO_char(sysdate,'DD/MM/YYYY'), 0),'MON') AND ADD_MONTHS(LAST_DAY(TO_char(sysdate,'DD/MM/YYYY')),0) AND PCORCAVENDAC.CODSUPERVISOR = PCPEDC.CODSUPERVISOR) QTORCAMENTOS,\n" +
            "        (SELECT COUNT(DISTINCT(PCORCAVENDAC.NUMPED)) FROM PCORCAVENDAC WHERE PCORCAVENDAC.DATA BETWEEN  trunc(ADD_MONTHS(TO_char(sysdate,'DD/MM/YYYY'), 0),'MON') AND ADD_MONTHS(LAST_DAY(TO_char(sysdate,'DD/MM/YYYY')),0) AND PCORCAVENDAC.NUMPED IS NOT NULL AND PCORCAVENDAC.CODSUPERVISOR = PCPEDC.CODSUPERVISOR) QTORCAMENTOCONVERTIDO,\n" +
            "        ROUND(SUM(NVL(DECODE(PCPEDC.CONDVENDA, 5, 0, 6, 0, 1, (SELECT COUNT(*) FROM PCPEDI I WHERE I.NUMPED = PCPEDC.NUMPED AND NVL(I.BONIFIC, 'N') = 'N'),14, (SELECT COUNT(*) FROM PCPEDI I WHERE I.NUMPED = PCPEDC.NUMPED AND NVL(I.BONIFIC, 'N') = 'N'), PCPEDC.NUMITENS), 0)),2) QTITENS, \n" +
            "        ROUND(AVG(NVL(PCPEDC.NUMITENS, 0)),2) MEDIAQTITENS,\n" +
            "        COUNT(DISTINCT(NVL(PCPEDC.CODCLI,0))) QTCLIPOS,                                                              \n" +
            "        ROUND(SUM(NVL(PCPEDC.TOTPESO,0)),2) TOTPESO,  \n" +
            "        ROUND(SUM(DECODE(PCPEDC.CONDVENDA,5,0,6,0,11,0,12,0,NVL(PCPEDC.VLATEND - NVL(PCPEDC.VLOUTRASDESP,0) - NVL(PCPEDC.VLFRETE,0)  ,0))),2) VLVENDAMES,\n" +
            "        MAX(NVL((SELECT SUM(NVL(PCMETASUP.VLVENDAPREV,0)) FROM PCMETASUP WHERE 0 = 0 AND PCMETASUP.DATA BETWEEN  trunc(ADD_MONTHS(TO_char(sysdate,'DD/MM/YYYY'), 0),'MON') AND ADD_MONTHS(LAST_DAY(TO_char(sysdate,'DD/MM/YYYY')),0)  AND PCMETASUP.CODFILIAL IN ('1','2','20','3','4','5','6','7','8','9') AND PCMETASUP.CODSUPERVISOR = PCPEDC.CODSUPERVISOR),0) ) METAMES,\n" +
            "        ROUND(NVL((SELECT SUM(DECODE(PED.CONDVENDA,5, 0 ,6, 0, 11, 0, 12, 0 ,NVL(PED.VLATEND - NVL(PED.VLOUTRASDESP,0) - NVL(PED.VLFRETE,0)  ,0))) VALOR FROM PCPEDC PED WHERE PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98) AND PED.DTCANCEL IS NULL AND PED.DATA = TO_CHAR(SYSDATE, 'DD/MM/YYYY') AND PED.CODSUPERVISOR = PCPEDC.CODSUPERVISOR AND PED.POSICAO = 'F'),0),2) VLVENDADIA, \n" +
            "        MAX(NVL((SELECT SUM(NVL(PCMETASUP.VLVENDAPREV,0)) FROM PCMETASUP WHERE 0 = 0 AND PCMETASUP.DATA BETWEEN TO_CHAR(SYSDATE,'DD/MM/YYYY') AND TO_CHAR(SYSDATE,'DD/MM/YYYY') AND PCMETASUP.CODFILIAL IN ('1','2','20','3','4','5','6','7','8','9') AND PCMETASUP.CODSUPERVISOR = PCPEDC.CODSUPERVISOR),0) ) METADIA\n" +
            "    FROM PCSUPERV, PCPLPAG, PCPEDC\n" +
            "    WHERE 1 = 1\n" +
            "      AND PCPEDC.CODPLPAG = PCPLPAG.CODPLPAG\n" +
            "      AND PCPEDC.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR(+)\n" +
            "      AND PCPEDC.CONDVENDA NOT IN (4, 8, 10, 13, 20, 98, 99)\n" +
            "      AND PCPEDC.DTCANCEL IS NULL\n" +
            "      AND PCPEDC.DATA BETWEEN  trunc(ADD_MONTHS(TO_char(sysdate,'DD/MM/YYYY'), 0),'MON') AND ADD_MONTHS(LAST_DAY(TO_char(sysdate,'DD/MM/YYYY')),0)\n" +
            "      AND PCPEDC.CODFILIAL IN ('1','2','20','3','4','5','6','7','8','9')\n" +
            "      AND PCPEDC.CODSUPERVISOR NOT IN (5)\n" +
            "      AND PCPEDC.CODSUPERVISOR = :P_LOJA\n" +
            "      GROUP BY PCPEDC.CODSUPERVISOR, NVL(PCSUPERV.NOME, '* NAO VINCULADO *')\n" +
            "    ORDER BY CODSUPERVISOR, VLVENDAMES DESC\n" +
            ")", nativeQuery = true)
    DashboardSupervisor getDadosDashboardSupervisor(@Param("P_LOJA") Long LOJA);
}
